### PR TITLE
Draft: use BigEndian order for Bolt to maintain correct ordering (closes #269)

### LINKED ISSUE #269: Robustness: DELA network breaks down after 256 rounds
after round 255 the following happens:

```
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z INF pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/core/ordering/cosipbft/mod.go:387 > block event addr=dela-worker-0:2000 index=256 root=b9bf9506
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z DBG pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/core/ordering/cosipbft/mod.go:551 > round has started addr=dela-worker-0:2000 index=257
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z DBG pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/core/ordering/cosipbft/blocksync/default.go:230 > received synchronization message addr=dela-worker-0:2000 index=255
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z WRN pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/mino/minogrpc/session/mod.go:398 > relay failed to send error="client: rpc error: code = Canceled desc = context canceled" addr=dela-worker-0:2000
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z WRN pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/mino/minogrpc/session/mod.go:398 > relay failed to send error="client: rpc error: code = Canceled desc = context canceled" addr=dela-worker-0:2000
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z WRN pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/mino/minogrpc/session/mod.go:374 > failed to setup relay error="client: rpc error: code = Canceled desc = context canceled" addr=dela-worker-0:2000 to=dela-worker-2:2000
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z ERR pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/mino/minogrpc/rpc.go:227 > stream to root failed error="rpc error: code = Unknown desc = handler failed to process: failed to verify chain: mismatch from: 'd6daf929' != '1894d9c4'"
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z WRN pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/mino/minogrpc/session/mod.go:389 > parent is closing error="client: rpc error: code = Canceled desc = context canceled" addr=Orchestrator:dela-worker-0:2000
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z WRN pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/core/ordering/cosipbft/blocksync/default.go:124 > announcement failed error="session Orchestrator:dela-worker-0:2000 is closing: Canceled" addr=dela-worker-0:2000
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z WRN pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/mino/minogrpc/session/mod.go:374 > failed to setup relay error="client: rpc error: code = Canceled desc = context canceled" addr=dela-worker-0:2000 to=dela-worker-3:2000

```
and then no new transactions can be added to the block chain anymore (i.e. no new forms, votes, ...)

I do not understand DELA enough to guess at an answer, the only thing that seems suspicious to me is the following line in the logs:

d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z DBG pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/core/ordering/cosipbft/mod.go:551 > round has started addr=dela-worker-0:2000 **index=257**
d-voting-dela-worker-0-1  | 2023-09-06T13:09:13Z DBG pkg/mod/go.dedis.ch/dela@v0.0.0-20221010131641-9c479e68be18/core/ordering/cosipbft/blocksync/default.go:230 > received synchronization message addr=dela-worker-0:2000 **index=255**

when before that the index has always been increasing

To reproduce: on a clean install, create a form and add votes up until 256

### PR DESCRIPTION
**Pull request by PascalinDe**
closes #269

### CODE REVIEW

**Comment by ineiti** [comment]
Just to make sure I looked at all `binary.LittleEndian` calls in Dela: can you confirm that the following line is NOT a problem, as it only uses the data, but not the key?

https://github.com/dedis/dela/blob/master/core/validation/simple/simple.go#L65

**Comment by PascalinDe** [comment]
> Just to make sure I looked at all `binary.LittleEndian` calls in Dela: can you confirm that the following line is NOT a problem, as it only uses the data, but not the key?
> 
> https://github.com/dedis/dela/blob/master/core/validation/simple/simple.go#L65

I'm not sure if that line is related to the key-value store in question, isn't it related to https://github.com/dedis/dela/blob/master/core/store/store.go?

the only places I found that handle the key of the Bolt store were in the same file as the change of this commit, and the key was only created, and used to retrieve data but not cast back to an uint64

**Comment by PascalinDe** [comment]
moved the PR to draft, as I'm still testing though

**Comment by PascalinDe** [comment]
tests look good so far (> 300 votes), but I had to test on https://github.com/dedis/dela/tree/fix-bbolt for d-voting, since d-voting is not working with the current head

**Review by pierluca — APPROVED** [review]

**Comment by ineiti** [comment]
Closing this for the new PRs

**Pull request closed without merging**
