### PR TITLE
dkgcli: return non-zero status on error

### PR DESCRIPTION
**Pull request by lourkeur**
Error propagation helps with debugging.

### CODE REVIEW

**Comment by pierluca** [comment]
Thanks @lourkeur . We'll look into addressing the issue you had with the CI.

**Review by jbsv — APPROVED** [review]

**Comment by lourkeur** [comment]
conflicts resolved

**Comment by pierluca** [comment]
#252 should resolve your CI issue.

**Comment by pierluca** [comment]
Closing this PR as it's been done already.

**Pull request closed without merging**
